# Generated by Django 5.1.6 on 2025-03-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='id_category',
            new_name='id_brand',
        ),
    ]
