# Generated by Django 5.1.6 on 2025-03-31 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_id_category_brand_id_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.user')),
            ],
            bases=('shop.user',),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.administrator'),
        ),
    ]
