# Generated by Django 5.1.6 on 2025-04-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_administrator_product_admin_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin_added',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
